### ISSUE TITLE
Encrypter error

### ISSUE THREAD

**Issue by lokeb** [wesharehoodies/laravel-5.4-crud-example#1]
I am getting this error on starting the app at http://localhost:8000 

> The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.
in Encrypter.php (line 43)
--

**Comment by wesharehoodies** [comment]
Try generating the app key:

`php artisan key:generate`

**Comment by lokeb** [comment]
That fixed it, thank you!
